"""empty message

Revision ID: 441386bea34e
Revises: a0b2fb4df442
Create Date: 2026-09-25 21:04:54.936500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441386bea34e'
down_revision = 'a0b2fb4df442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
