"""empty message

Revision ID: 9193a3a0a87e
Revises: d44e2beaf2cd
Create Date: 2026-09-28 19:27:55.850663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9193a3a0a87e'
down_revision = 'd44e2beaf2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
